version: '3'
services:
  pgdatabase:
    container_name: postgres_db
    image: postgres:13
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=workshop
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
